### ISSUE TITLE
What will happen if steam broken accidently?

### ISSUE THREAD

**Issue by kkzhang** [G-Research/grpc_async_examples#3]
I am new comer to c++&grpc, after read your example code: **async_streaming_server_alarm.cc**, i don't understand what will happen if stream rpc call was broken accidently.

In such cases, CallData seems have no chance to delete itself.

Maybe i can use **AsyncNotifyWhenDone()** to release memory of CallData ?

**Comment by honghaichu** [comment]
The status of `CallData` is modified by the server, in this example it will be set to `FINISH` after processing 6 times regardless of the state of the rpc.
This is an async server, so be design it's not waiting for any notifications from the client.

**Comment by kkzhang** [comment]
Thank you for quick reply.

So for this example, i suppose, there is not task generated by server in such cases:

1. client close connection
2. client interrupt rpc call
3. connection broken

And I notice the example use this line to control the process:

```cpp
void PutTaskBackToQueue()
{
           alarm_.Set(cq_, gpr_now(gpr_clock_type::GPR_CLOCK_REALTIME), this);
}
```
Is it too `heavy`? (too much resource consumption, because it runs again and again for nothing to do)
Why not just idle the task, and push task to queue if there are some data to write?

**Comment by honghaichu** [comment]
I think what you want is a synchronous client-server connection, which is not covered by these examples. You can go to gRPC's official repo and have a look at the synchronous examples there.

The short answer is there's no other simple way to put a task back to the queue (at least at the time writing). You can read more about it in our blog post: https://www.gresearch.co.uk/article/lessons-learnt-from-writing-asynchronous-streaming-grpc-services-in-c/
